Add missing 'www' in the patch url.
Without 'www', 'brew install cmake' would produce the following error, at least on OSX 10.6.8:

$ brew install cmake
==> Downloading http://www.cmake.org/files/v2.8/cmake-2.8.5.tar.gz
######################################################################## 100.0%
==> Downloading patches
curl: (6) Couldn't resolve host 'cmake.org'
Error: Failure while executing: /usr/bin/curl -f#LA Homebrew\ 0.8\ (Ruby\ 1.8.7-174;\ Mac\ OS\ X\ 10.6.8) http://cmake.org/gitweb?p=cmake.git;a=patch;h=702538eaa3315f3fcad9f1daea01e6a83928967b -o 001-homebrew.diff