git-annex: drop require "formula"
because `brew audit --strict git-annex` outputs
```
==> audit problems
git-annex:
 * `require "formula"` is now unnecessary
```

Error: 1 problems in 1 formulae