README.md: brew update requires git 1.7.12.4
$ brew update
error: unknown option `short'
usage: git symbolic-ref [options] name [ref]

Closes Homebrew/linuxbrew#568