bbcp: fix implicit int build error with patch
This commit fixes a build failure caused by `main`'s use of an implicit
`int` return type specifier.

The embedded patch just makes the return type explicit.

ISSUE

As of C99, a declaration that lacks a type specifier isn't implicitly
assumed to be int, which causes the build to fail with this error:

    bbcp.C:61:1: error: C++ requires a type specifier for all declarations
    main(int argc, char *argv[], char *envp[])
    ^~~~

ENVIRONMENT

- g++ : Apple LLVM version 5.0 (clang-500.2.76) (based on LLVM 3.3svn)
- OS  : Mac OS X 10.8.5 (Build 12F37)

NOTES

- Confirmed Formula passes audit.
- Also sent the patch to the upstream developer.

Closes #22832.

Signed-off-by: Adam Vandenberg <flangy@gmail.com>