opusfile 0.1
The opusfile library provides a high-level API for decoding
and seeking in .opus audio streams, including over http.

This formula depends on openssl for https support because of

  ld: symbol(s) not found for architecture x86_64

with the Apple version of openssl on MacOS 10.7.5.

The system ssl library should work, and indeed it does if I
do a naive './configure && make' in the normal environment.
Something about the brew environment seems to confuse the linker.