pull: don't try to publish nonexistent bottles
```
Fast-forward
 Library/Formula/ant.rb     |  8 ++++----
 Library/Formula/nailgun.rb | 10 +++++-----
 2 files changed, 9 insertions(+), 9 deletions(-)
Deleted branch pull-bottle-45902 (was 1fdb73d).
==> Publishing on Bintray:
{"files":3}
==> Publishing on Bintray:
Error: Failure while executing
```

In that case, "jetty-runner" is bottle unneeded, but because I've passed the
pull bottle command for the other two formulae, it attempts to publish a bottle
that isn't there.