brew-create: don't break when given --set-version
Since 9f2782812cbaf2, specifying a version breaks with:

    Error: undefined method `detected_from_url?' for "1.2.2":String

Signed-off-by: Adam Vandenberg <flangy@gmail.com>