Add missing boost dependency
Fixes failure to build on OSX 10.7.5 with error ./src/errors.hpp:214:10: fatal error: 'boost/version.hpp' file not found