git: fix broken svn option if no swig exists prior.
Resolves the bug where installing Git with brewed-svn wouldn't
automatically drag in the required Swig dependency and consequently
the build would instantly error out.

The error itself could be with the subversion formulae or Homebrew
itself, and this may just be a workaround. Given building git
with-brewed-svn specifies svn with perl, it should trigger a swig
download automatically prior to attempting to install the svn dep,
but for some reason it doesn't.

Both from-source and from-bottle installs error out in the same way:

```
==> Installing git dependency: subversion
Error: /usr/local/opt/swig not present or broken
Please reinstall swig. Sorry :(
```

For now, have resolved this bug by dragging in an explicit swig
dependency prior to the subversion one, if you choose to install
with-brewed-svn.

Closes #34554.

Closes #34576.

Signed-off-by: Mike McQuaid <mike@mikemcquaid.com>