resolve lrzsz package download using mirror
The author's https download site certificate has expired,

```
ERROR: cannot verify ohse.de's certificate, issued by 'CN=StartCom Class 1 Primary Intermediate Server CA,OU=Secure Digital Certificate Signing,O=StartCom Ltd.,C=IL': Issued certificate has expired.
```

or, from brew through curl,

```
curl: (60) SSL certificate problem: Invalid certificate chain
```

This prevents package installation. Suggest fedora project archive
copy at stable url by md5 hash as mirror.

Fedora url does not redirect to https. https at the Fedora url is
'self signed', so http is used here.  The author's address when
accessed by http will redirect to https, resulting in error.

I have notified the author/maintainer.  Have not heard back.