audit: don't check recursively unconditionally
There's an issue with either brew or (seemingly more likely) Ruby that blocks
this check from running successfully if you have more than a certain number or
specific taps tapped.

The error is:
```
Error: stack level too deep
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:333
```

This has been killing builds off in the various taps. This isn't really a long-term
solution but for now it at least allows builds to proceed whilst we spend some more
time getting familiar with this problem.

I went down the `ENV` route because this bug reproduces locally against the core
with taps present, so for example I cannot currently run any `brew test-bot`
commands against core formulae without it hanging and then dying on that message.
We can pass the ENV selectively to Travis and Jenkins in the core easily, so
it seems like a nice compromise.