Change default compiler for gnu-cobol to GCC
The default clang version bundled with Mac OS X causes a reproduceable error when compiling e.g. CobolUnit.
The resulting message is:
error: indirect goto in function with no address-of-label expressions
This patch uses GCC as default compiler which works fine.