bash: add devel block
The current testing release is 4.4-beta.

Also, discard the --with-installed-readline option when building devel
or head, since the devel or head of bash may use an unreleased GNU
readline library. For instance, building bash 4.4-beta with readline
6.3.8 results in the following errors:

    Undefined symbols for architecture x86_64:
      "_history_lines_read_from_file", referenced from:
          _load_history in bashhist.o
          _history_builtin in libbuiltins.a(history.o)
      "_history_lines_written_to_file", referenced from:
          _maybe_save_shell_history in bashhist.o
      "_rl_redraw_prompt_last_line", referenced from:
          _bash_execute_unix_command in bashline.o
    ld: symbol(s) not found for architecture x86_64

Closes #47596.

Signed-off-by: Mike McQuaid <mike@mikemcquaid.com>