setuptools upgrade is required on 10.6
during the saltstack step ...

```
==> Installing saltstack
==> Downloading https://pypi.python.org/packages/source/s/salt/salt-0.17.2.tar.gz
==> Downloading https://pypi.python.org/packages/source/p/pycrypto/pycrypto-2.6.tar.gz
==> /Library/Frameworks/Python.framework/Versions/2.7/bin/python setup.py install --prefix=/usr/local/Cellar/saltstack/0.17.2/libexec
==> Downloading https://pypi.python.org/packages/source/P/PyYAML/PyYAML-3.10.tar.gz
==> /Library/Frameworks/Python.framework/Versions/2.7/bin/python setup.py install --prefix=/usr/local/Cellar/saltstack/0.17.2/libexec
==> Downloading https://pypi.python.org/packages/source/p/pyzmq/pyzmq-14.0.0.tar.gz
==> /Library/Frameworks/Python.framework/Versions/2.7/bin/python setup.py install --prefix=/usr/local/Cellar/saltstack/0.17.2/libexec
==> Downloading https://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.4.0.tar.gz
==> /Library/Frameworks/Python.framework/Versions/2.7/bin/python setup.py install --prefix=/usr/local/Cellar/saltstack/0.17.2/libexec
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from setuptools import setup, Extension
ImportError: No module named setuptools
```

Used `pip` to upgrade an existing version of *setuptools 0.6c9* on test *OS X 10.6*.  For now, my install script forces the upgrade (`pip install setuptools --upgrade`) before running `brew install saltstack`.

Not sure if I edited this file right.  Just trying to help out with some of the leg work.