Added ENV.deparallelize in syck.rb because GCC fails on bytecode.c which requires a generated gram.h
The build process uses Bison for generating a series of files, including gram.h before compiling bytecode.c.

Unfortunatelly, when using Homebrew the compilation process fails on bytecode.c because GCC gets called before Bison finishes generating gram.h.

The error message without using ENV.deparallelize is the following:

/bin/sh ../config/ylwrap gram.y y.tab.c gram.c y.tab.h gram.h y.output gram.output -- bison -y  -d -t -v -p syck
/usr/bin/gcc-4.2 -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I..   -fPIC -w -pipe -O3 -c bytecode.c
bytecode.c:15:18: error: gram.h: No such file or directory
bytecode.c:138: error: expected ‘)’ before ‘*’ token