Fixed an error where `gcc` was available, but brew failed because it has checked for XCode presence
The error was: "undefined method `<' for nil:NilClass", coming from Library/Homebrew/extend/ENV.rb:140

This prevented installing for users who have downloaded "standalone" compilers
eg. from <https://github.com/kennethreitz/osx-gcc-installer>.