Update pngcrush to version 1.7.46
Fixes issue with missing 1.7.43 version:

```
brewmaster:~ mrickert$ brew install pngcrush
Warning: Your Xcode (4.5.2) is outdated
Please install Xcode 4.6.
==> Downloading http://downloads.sourceforge.net/project/pmt/pngcrush/1.7.43/pngcrush-1.7.43.tar.gz

curl: (22) The requested URL returned error: 404
Error: Download failed: http://downloads.sourceforge.net/project/pmt/pngcrush/1.7.43/pngcrush-1.7.43.tar.gz
```