Fix ttytter installation failure caused incorrect checksum
When trying to install ttytter 2.1, the following checksum error appeared:
$ brew install ttytter
==> Downloading http://www.floodgap.com/software/ttytter/dist2/2.1.00.txt
Error: SHA1 mismatch
Expected: dd20d55aa819699b3e39ca4c35bf390b3e074db3
Actual: a72b2c4b7da8a370ff15c7f5a1a3ecf9056590f0
Archive: /Library/Caches/Homebrew/ttytter-2.1.00.txt
The formula is fixed with new checksum.